- PLUGINS-LIST.md
- README.md
- plugins/markerTagToScene/markerTagToScene.js
- plugins/markerTagToScene/markerTagToScene.yml
Adds hooks on Scene Marker create and update. Adds the primary tag of the scene marker to the scene.
Also includes initial documentation for the repo.
Resolves stashapp/stash#1011
> Marker tag to scene

- plugins/renamerOnUpdate/renamerOnUpdate.py
My local version don't care if the file exist or not, but i think for most people it would be annoying that the rename don't work but rename the DB.
> [Hook Rename] Prevent rename db if file don't exist/failed

- PLUGINS-LIST.md
- plugins/filenameParser/filenameParser.js
- plugins/filenameParser/filenameParser.yml
Add a plugin which tries to parse the names of scenes and galleries when they're added / scanned. The primarily supported format is `{studio}.{year}.{month}.{day}.{performer}.{performer}.{title}`. Studio can optionally include ".com". Some "parts" are ignored like resolution, some release group names etc. Performers can be separated by an optional "and" which will be ignored as well. Performers are both searched based on name and aliases, for which aliases are split based on `,` and `;` and needs to result in an "exact" match meaning "First Last" won't match a performer which name or alias is just "First". When there are multiple
matches (for example when filename is "first1.first2.last2" and multiple performers having the "first1" alias) all matched performers will be added.
> Add plugin which parses scene and gallery filenames on add

- plugins/renamerOnUpdate/README.md
- plugins/renamerOnUpdate/config.py
- plugins/renamerOnUpdate/renamerOnUpdate.py
- plugins/renamerOnUpdate/renamerOnUpdate.yml
Add new filename fields:
- scene rating with pre or post string options (e. g.: 'RTG5')
- tags list to add all linked tags included/excluded by whitelist and blacklist
New configurations:
- Replace spaces with another character (e. g.: gain period separated filenames)
- Squeeze studio names
> [renamerOnUpdate] Add scene rating and tags as fields + additional configurations

- plugins/renamerOnUpdate/renamerOnUpdate.py
- plugins/renamerOnUpdate/renamerOnUpdate.yml
I noticed that the code at https://github.com/stashapp/CommunityScripts/blob/3a321a06c9fcaa4db8fe8c651a6577a85e3258a6/plugins/renamerOnUpdate/renamerOnUpdate.py#L301-L303 wasn't retrieving the template for the parent studio but the current studio.
I changed it so that it recursively searches for templates of parent studios BUT stops at the first template found. This makes it possible to have a different template for just a single subsidiary studio.  
The alternative would be to traverse all parent studios and take the highest one in the chain.
> [renamerOnUpdate] Search recursively for parent studio template

- plugins/renamer/renamerTask.py
While running this on Windows I was getting an error due to a charset mismatch. The default encoding on Windows is not UTF-8 so, since we're using it while writing the file, we should make sure we're using it while reading the dry run file.
> [renamer] Enforce utf-8 encoding when opening FILE_DRYRUN_RESULT

- README.md
- plugins/renamerOnUpdate/README.md
- plugins/renamerOnUpdate/config.py
- plugins/renamerOnUpdate/renamerOnUpdate.py
- plugins/renamerOnUpdate/renamerOnUpdate.yml
- Template to move your files 
- Bulk task to rename all your scenes with a button #66 
- Dry-run (Do a trial run with no permanent changes)
- More field (mostly movie related)
- option to sort of the order of performer (Name, ID, Favorite, Rating)
- option to keep performer if it reach the performer limit
- group in template, you can group character with `{}`. kinda #68
Exemple: `[$studio] {$date -} $title` The `-` is with the date, so if the date is empty, `-` will be remove as well
- Add a option to replace thing in your filename. (#67)
The second element of the list determine the system used. If you don't put this element, the default is word
`regex`: match a regex, `word`: match a word, `any`: match anything
difference between `word` & `any`: word is between seperator (`space  _ …
> [renamerOnUpdate] Major Update (Bulk, Mover...)

- README.md
- plugins/pathParser/README.md
- plugins/pathParser/pathParser.js
- plugins/pathParser/pathParser.yml
Path Parser shares some similarities with filenameParser and defaultDataForPath.
Unlike those examples, it allows more advanced matching capabilities against the file path for scenes and can update scene attributes based on sub-expression in the path.
For example, if there is a folder for a movie named "Movie Name (2010)" and the scene is split into multiple files "Scene Title - Scene [N].mp4" it can extract/update Movie Name and Scene Title.
It supports updating scenes tagged with [Run], testing rules against scenes tagged with [Test], and automatically updating scenes as they are scanned.
> [PathParser] Plugin

- plugins/renamerOnUpdate/renamerOnUpdate.py
- plugins/renamerOnUpdate/renamerOnUpdate.yml
Because this check was using `in`, using the Dry Run setting from inside the Stash UI was destroying the `dry_run_append` config value (by making it another `dry_run` value), thereby breaking the config. As it turns out `dry_run` is both in `dry_run` **and** `dry_run_append`. `config_edit` appears to only be used in cases with strict config value matching so I don't expect this loose comparison is an expected behavior.
> [renamerOnUpdate] Perform a stricter check in config_edit to avoid breaking the config

- plugins/GHScraper_Checker/GHScraper_Checker.py
- plugins/GHScraper_Checker/GHScraper_Checker.yml
Currently, if/when this script detects a scraper file in a subdirectory, it misreports it as missing in the root scrapers directory and will also write the file there. I've gotten a bit more hands-on time with Python since the last time I contributed stuff in here, but it's definitely still not my strongest language so please let me know if there's any better ways to solve this (regex tends to feel like a code smell to me in situations like this) or if there's gotchas I've missed.
After this I'm kinda leaning towards getting this script able to handle the entirety of the directory. I don't love that, especially as the scrapers get progressively custom, this script is ignoring the python scripts.
> [GHScraper] Fix support for subdirs

- plugins/DateParser/date_parser.py
- plugins/DateParser/date_parser.yml
- plugins/DateParser/requirements.txt
Simple plugin that add a new task allowing you to scan galleries without a date and try to find the date from its path (inclusing filename).
Example working date : 
Oct. 15, 2002
15 October 2022
15/10/2022
15/10/22
15-10-2022
etc
Require stashapi and dateParser. Requirement.txt included
> Gallery DateParser - Parse dates from filenames & path for galleries

- plugins/renamerOnUpdate/renamerOnUpdate.py
- plugins/renamerOnUpdate/renamerOnUpdate.yml
Adds duplicate handling of same filename of different scenes testing all duplicate_suffix config variables before aborting.
> [renamerOnUpdate] handling of duplicate filenames of different scenes

- plugins/timestampTrade/README.md
- plugins/timestampTrade/requirements.txt
- plugins/timestampTrade/timestampTrade.py
- plugins/timestampTrade/timestampTrade.yml
I've created the api https://timestamp.trade to sync markers between stash instances and xbvr.
This sits along side other metadata databases like stashdb while we wait for the feature to be added there.
> Timestamp.trade

- plugins/timestampTrade/timestampTrade.py
- plugins/timestampTrade/timestampTrade.yml
Calling the stash graphql api manually as I only care about a few fields when submitting data.
Improved logging message and report % of files being processed.
Use a persistent session with timestamp.trade instead of connecting for each request.
> Fixing bugs with the plugin with submission.

- plugins/1. stashUserscriptLibrary/StashUserscriptLibrary.yml
- plugins/1. stashUserscriptLibrary/stashUserscriptLibrary.js
- plugins/2. stats/stats.js
- plugins/2. stats/stats.yml
- plugins/3. Stash Batch Result Toggle/stashBatchResultToggle.js
- plugins/3. Stash Batch Result Toggle/stashBatchResultToggle.yml
I've refactored @7dJx1qP/redsheep1's  Stash Userscript Library such that it can be used for plugin development directly into Stash. That library has made it easy for many users to build on, to create various user scripts. My thinking is that if the library was made available for plugin development, user scripts that could have been provided as a plugin could easily be transitioned into a plugin.
You must ensure the library is loaded before other scripts, so I have numbered the directories to enforce a load order. From there, I basically copied the content of the Stash Stats user script and provided it as its own plugin.
> Stash userscript library

- plugins/comicInfoExtractor/README.md
- plugins/comicInfoExtractor/comicInfoExtractor.py
- plugins/comicInfoExtractor/comicInfoExtractor.yml
- plugins/comicInfoExtractor/config.yml
- plugins/comicInfoExtractor/requirements.txt
As the name proposes, this Plugin adds support for importing metadata from the ComicRack Standard for cbz files.
This data is saved in a ComicInfo.xml file in the archive on the top level, containing certain Tags with metadata.
As it is not exactly possible to match everything with stash 1:1, I added a yml file with a dictionary that matches the XML Tags with the variables of a stash gallery. 
The current values are what I use, but I've already added stuff into the code to be able to work with every value a stash gallery can have.
The default dictionary can be changed, probably the writer:studio matching is the most controversial. 
For more info on the standard, you may look to into
https://github.com/comictagger/comictagger
Also, right now, the data is always applied when updating a …
> Add a ComicRack Metadata Extractor for cbz based Stash Galleries

- build_site.sh
- plugins/comicInfoExtractor/config.yml
Changed the site building script to ignore yml files when they contain `#pkgignore`
> Use #pkgignore to omit from build script

- scripts/stash-watcher/README.md
the sample Docker compose spacing is reported wrong, adjusting to close #196
> Fixes spacing to close #196

- plugins/renamerOnUpdate/README.md
- plugins/renamerOnUpdate/renamerOnUpdate.py
- plugins/renamerOnUpdate/renamerOnUpdate.yml
As the README says:
It is labeled 2.5.0, to fill the gap until v3.0 is released
It is NOT heavily tested, with the bare minimum needed to work with Stash v24
Version 3 is a major rewrite, but since it's not quite ready, pushing 2.5.0 seems necessary
It worked for me, using my old config, and I got no errors during my limited tests.
YOU HAVE BEEN WARNED - any potential data loss is on you.
BEFORE YOU USE IT TO MOVE/RENAME ANYTHING CRITICAL, test it yourself.
I still suggest you wait for v3, but... if you can't, this is now out.
> v2.5.0 - limited changes to work with Stash v24 - STOPGAP RELEASE

- plugins/timestampTrade/timestampTrade.py
- plugins/timestampTrade/timestampTrade.yml
If someone has linked a scene to a movie and submitted the data there can be movie information in timestamp.trade. If enabled a movie will be created and the scene number linked on save.
If the extra urls have been submitted to timestamp.trade add them to the scene. I am hoping to crowd source links to funscripts for example.
> Adding Movie sync support and extra urls from timestamp.trade

- plugins/timestampTrade/timestampTrade.py
Bugfix, set a default value for the config option as it does not exist in the plugin config until the value has been set.
> bugfix,  timestampTrade.py set a default config value

- plugins/miscTags/miscTags.py
- plugins/miscTags/miscTags.yml
This plugin parses file names for VR useful for stash-vr-companion.
File names in vr have file names like: povr-originals-work-to-liv-or-liv-to-work-180_180x180_3dh_LR.mp4
180x180 indicates 180° projection.
LR indicates it is left right side by side.
For stash-vr-companion add the export_deovr, DOME, SBS tags if you have the setting enabled.
Add the 180°, Virtual Reality or what you have configured in your settings as the vr tag if you have the setting enabled.
I also want to automatically tag 2d scenes based on the studio so set the local studio id in stash ie studio 4 in your instance is Girls Out West so add export_deovr, FLAT to all scenes in this studio.
> Adding miscTags plugin for VR

- plugins/stashdb-performer-gallery/requirements.txt
- plugins/stashdb-performer-gallery/stashdb-performer-gallery.py
- plugins/stashdb-performer-gallery/stashdb-performer-gallery.yml
Adding a new plugin to automatically download performer images from stashdb or any other stash-box instance.
Add the tag [Stashbox Performer Gallery] to a performer to start the background job. The images will be downloaded and added to a gallery for the database.
You can then go into the gallery and add the tag [Set Profile Image] to an image with exactly 1 performer to set that image as the profile image.
> Adding a new plugin to automatically download performer images from stashdb

- plugins/stashUserscriptLibrary/stashUserscriptLibrary.js
Now display events are handled better and all mutation listener functions now closes instead of holding the code even on page change and mutation disconnect.
Added support to:
1. `:grid`
2. `stash:page:any:tabname:viewtype`
3. `stash:page:pagename:any:viewtype`
No breaking changes. Prob my final PR for page listeners as I have implemented every single possible page and element combinations.
> re-implemented display view events

- plugins/stashUserscriptLibrary/stashUserscriptLibrary.js
"stashUserscriptLibrary" currently not working on stash installations with a baseURL, example "https://my.host.co/stash/" has "stash/" as the baseURL. "stashUserscriptLibrary" always uses "/".
> [stashUserscriptLibrary] Use `baseURL` for stash, if available

- plugins/TPBDMarkers/TPDBMarkers.yml
- plugins/TPBDMarkers/requirements.txt
- plugins/TPBDMarkers/tpdbMarkers.py
This plugin fetches markers from TPDB for scenes when tagged using their stash-box endpoint.
This uses the api key as configured in the endpoint settings.
> This plugin fetches markers from TPDB when tagged using their stash-box endpoint

- plugins/TPBDMarkers/TPDBMarkers.yml
- plugins/TPBDMarkers/tpdbMarkers.py
- plugins/timestampTrade/timestampTrade.py
- plugins/timestampTrade/timestampTrade.yml
I add settings to two scene marker plugins. Hooks can be disabled by user without disabling whole plugin. This way tasks remain active and can be called when needed.
> Allow disabling scene marker hooks

- plugins/renamerOnUpdate/.gitignore
- plugins/renamerOnUpdate/renamerOnUpdate.py
don't track the customized config file for ROU so on update changes to the config are not squashed
The current preference is for the plugin to use the template before the custom config file, this inverts that and will first attempt to load the custom config before the template
> [renamerOnUpdate] Untrack custom config and load it first if present

- plugins/phashDuplicateTagger/phashDuplicateTagger.py
variables passed as a set when it needs to be a dict
> PDT bugfix

- plugins/defaultDataForPath/defaultDataForPath.js
Fix error : 
```
Scene.Create.Post [Default Data For Path]: returned error: Error: graphQL query failed: 422 - {"errors":[{"message":"Cannot query field \"path\" on type \"Scene\". Did you mean \"paths\" or \"date\"?","locations":[{"line":1,"column":59}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}}],"data":null}. Query: query findScene($id: ID) {    findScene(id: $id) {        path    }}. Variables: map[id:13785]
```
> [defaultDataForPath] fix GRAPHQL_VALIDATION_FAILED on scene post

- plugins/VideoScrollWheel/VideoScrollWheel.yml
- plugins/VideoScrollWheel/videoScrollWheel.js
allowVolumeChange to let the user decide if volume changing via mouse wheel is enabled. Blocks accidental volume changes.
> VideoScrollWheel: Add new option for volume change

- plugins/miscTags/miscTags.py
noticed that it's tagging 360_TB files with SBS when (i'm assuming) it should be TB. Fixed in this commit
> Update miscTags.py (#1)

- .editorconfig
- plugins/stashdb-performer-gallery/stashdb-performer-gallery.py
- plugins/stashdb-performer-gallery/stashdb-performer-gallery.yml
- plugins/timestampTrade/timestampTrade.py
- plugins/timestampTrade/timestampTrade.yml
Updating timestamp.trade and stash-performer-gallery for better background processing.
For timestamp.trade scene updates trigger a background task to do the processing so the scene update is not blocked.
A timestamp.trade url can be added to a scene and if this is present it will look up scene metadata for updates.
This allows you to re-process scenes for movie and gallery information after the initial task.
stashdb-performer-gallery has been updated to process in background jobs.
> Updates to timestamp.trade and stashdb-performer-gallery

- plugins/discordPresence/README.md
- plugins/discordPresence/discordPresence.js
- plugins/discordPresence/discordPresence.yml
Found an edge case bug where sending malformed URLs would lock up the RPC server and/or the Discord client and freeze the displayed presence. Also changed some README table column ordering and bumped plugin version to 1.0 as this is pretty much as feature-rich as it's going get.
> Fix URL bug, bump to 1.0

- plugins/markerTagToScene/markerTagToScene.js
Not sure when this happened but the input to Javascript plugins appears to be PascalCase instead of snake_case now so this plugin wasn't working
I also changed it so that it adds not just the primary tag from the marker but also any additional tags, if present
> Update markerTagToScene for new Javascript runtime

- plugins/qxSceneCard/qxSceneCard.css
- reverse proxy basepath agnostic
- plugin name agnostic
This sets assets to already be at `/plugin/{ID}/`
> Relative URLs, if used, are relative to the URL of the stylesheet (not to the URL of the web page).
https://developer.mozilla.org/en-US/docs/Web/CSS/url
> use relative path for assets

- plugins/phashDuplicateTagger/config_example.py
- plugins/phashDuplicateTagger/phashDuplicateTagger.yml
The "self" scene was always returned meaning it would always be tagged as the scene to keep.
Return the better scene object as per the expected behaviour.
> [PDT] fix compare_encoding return value

- plugins/defaultDataForPath/defaultDataForPath.js
input.Args.hookContext object attribute `ID` seems to have been renamed to `id`
> Update defaultDataForPath.js to work with possible updated hookContext

- plugins/miscTags/miscTags.py
- plugins/miscTags/miscTags.yml
This should expand the group makeup tags so if there is the foursome tags and you have 3 female performers and one male it will add the tag "Foursome (BGGG)".
For sites that do not include the male there is a setting to assume they are male so a "Fivesome" with 3 female performers added to the scene will end up with the "Fivesome (BBGGG)" tag.
If there are missing performers and this setting is turned off there are unknown performers and no group makeup tag will be added.
> Updating misc-tags to add more group makeup options for foursome, fivesome, sixsome, sevensome.

- plugins/VideoScrollWheel/VideoScrollWheel.yml
- plugins/discordPresence/discordPresence.yml
- plugins/stats/stats.yml
`#requires:` specifically needs a space - these packages were parsed without the csUiLib requirement
> fix requires syntax

- plugins/AITagger/ai_tagger.py
assign increment after `if` to avoid div by zero error
> [AITagger] bugfix

- plugins/hotCards/README.md
- plugins/hotCards/hotCards.css
- plugins/hotCards/hotCards.js
- plugins/hotCards/hotCards.yml
card_opts allows you to specify whether you want the card to be filled or not, and also set the opacity of the card. This addresses the case where the user wants only the border of the card to be colored.
Other changes:
- Adjust README to include the new option and other additions.
- Change misleading param name 'border_opts' to 'hover_opts' in the docs, code and in the configuration file.
- Update version to 1.1.2.
> [Hot Cards] Add card_opts as new optional parameter

- plugins/VideoScrollWheel/VideoScrollWheel.js
- plugins/VideoScrollWheel/VideoScrollWheel.yml
This fixes an issue where the time change applied may not work if the delta is too small. I've only observed this being an issue while transcoding a video, direct streams do not seem to ever have this problem.
> [videoScrollWheel] Fix issue where time change could be ignored

- plugins/hotCards/README.md
- plugins/hotCards/hotCards.js
- plugins/hotCards/hotCards.yml
Multiple styles can now be applied to the same page depending on the rating values or tag values configured for each type of card.
This update won't break the current configured settings of any user, but it will allow for more flexibility.
> [Hot Cards] Add multi-tag and multi-style support

- plugins/RenameFile/README.md
- plugins/RenameFile/renamefile.py
- plugins/RenameFile/renamefile.yml
There's was an (if not) condition which should have been an (if) condition. This caused issues when renaming a file without populating the title field and with an associated performer.
Sorry for the extra logging changes, but I had to throw in a lot of logging to find this bug, and I didn't want to remove it in case it's needed again.  The extra logging doesn't log unless user has the Debug-Trace option enabled.
> [RenameFile] Fixed bug associated with rename

- plugins/timestampTrade/timestampTrade.py
- plugins/timestampTrade/timestampTrade.yml
Bugfixes and adding a feature to download images if they exist in timestamp.trade
There can be a few images that go along with the scene that xbvr scrapes so if configured it will download these images and create a gallery linked with the scene. The [Timestamp: Auto Gallery] tag needs to be added to the scene to use this feature.
> [Timestamp Trade] Fixes and new feature to download images

- plugins/hotCards/hotCards.css
- plugins/hotCards/hotCards.js
- plugins/hotCards/hotCards.yml
- plugins/hotCards/utils/helpers.js
- plugins/hotCards/utils/registerPathChangeListener.js
- Fix holo effect not showing on home page
- Fix duplication of hot card elements by properly handling navigation events.
Duplication of elements was not noticeable until the holo style was introduced, which in case of duplication, becomes evident in the DOM.
> [Hot Cards] Fix element duplication and missing homepage holo effect

- plugins/markerDeleteButton/markerDeleteButton.css
- plugins/markerDeleteButton/markerDeleteButton.js
- plugins/markerDeleteButton/markerDeleteButton.yml
This adds the markerDeleteButton plugin. This is a very small plugin that just adds a `Delete` button to entries on the Markers page. Clicking this will delete the associated Marker through GQL and reload the page. The button is hidden until the user hovers over the Marker entry on the page and then is low opacity until hovering over the button.
I considered adding a confirmation upon clicking the button, but the odds of a misclick seem relatively low to me. If people use this plugin and end up wanting that though, I could add it as a configurable option.
I can't really say how many people will want this plugin. For me, I use Markers as more of a highlights/favorites feature, and when I come across a marker with a boring preview that I want to get rid of, the current process of deleting …
> Add markerDeleteButton plugin.

- plugins/VideoScrollWheel/VideoScrollWheel.js
- plugins/VideoScrollWheel/VideoScrollWheel.yml
When scrolling to time skip near the start or end of the video, the plugin would enter an infinite loop and crash the tab/browser. If the time delta would cause this to happen, the plugin will now set the video to the very start/end and break the loop.
> [VideoScrollWheel] Fix infinite loop when scrolling near start/end

- plugins/markerDeleteButton/markerDeleteButton.js
- plugins/markerDeleteButton/markerDeleteButton.yml
This is especially useful when reviewing markers created by Skier's AI model.
Known issues: If a new marker is created or an existing marker edited, Delete buttons are no longer visible when returning to the page. csLib.PathElementListener only activates when the user navigates to the page after which the specific element must appear. When moving from Create or Edit forms back to the list of markers there is no navigation event and thus Delete buttons will not be re-created.
> [markerDeleteButton] Delete buttons on Scene page next to Edit button

- plugins/timestampTrade/timestampTrade.py
- plugins/timestampTrade/timestampTrade.yml
A few more features, funscripts matching, excluding markers with matching strings and adding a string to new markers.
Indexing funscripts is done with a task creating a database with the funscript path and a md5 of the script. Submitting funscripts is done by the submit tasks. On query a list of funscript hashes are returned by the api and if thre is a matching script it will copy the file to the correct name for stash to match it.
Added an option to exclude markers that contain a string.
Added an option to add the [Timestamp] tag to markers the plugin creates.
Added an option to add the string [TsTrade] to markers eg "[TsTrade] marker name".
And bugfixes
> A few more features, funscripts matching, excluding markers with matching strings and changes to marker titles and tags

- plugins/audio-transcodes/audio-transcodes.py
- plugins/audio-transcodes/audio-transcodes.yml
If there is an audio file (width and height is 0), generate a transcode.
This will convert the audio file to a video with a solid blue colour.
If a transcode file is found for the scene it will use that instead of the original file.
This is a file typically in /generated/transcodes/ohash.mp4 or /generated/transcodes/md5.mp4.
This allows the normal video player to be used.
> Adding a new plugin audio-transcodes.

- plugins/funscriptMarkers/funscriptMarkers.py
- plugins/funscriptMarkers/funscriptMarkers.yml
Funscripts can potentially include "chapters" in the metadata that goes along with the script.
If there is a matching funscript ascociated with the scene (video.mp4 and video.funscript).
if the author of the script has included "chapters" in the metadata create markers for the scene.
> Adding a plugin to get markers from funscripts.

- userscripts/StashDB_Submission_Helper/stashdb_submission_helper.user.js
- Change the original if-else chain to iterate through the urlPatterns array
- Each urlPattern object contains pattern and site attributes
- Use regular expressions to test the URL and return the corresponding site name
- Added regular expression matching rules for some additional sites
- Set "Studio Profile" as the default return value for the urlSite().
> Refactor URL detection logic to match sites

- plugins/hotCards/hotCards.yml
- plugins/hotCards/utils/helpers.js
This ensures 'activeHotCardTypes' is cleared when the user navigates backwards, allowing 'createAndInsertHotCards' to be run when there is the same type of hot card active in two subsequent navigations.
> [Hot Cards] Add missing popstate event listener

- plugins/tagScenesWithPerfTags/tagScenesWithPerfTags.py
tagScenesWithPrefTags has a problem where it comes in a loop of calling itself.
This checks for the length of the update keys, which would be greater than 2 when manually updating a scene. But when the plugin updates it, it is only 2 ("ids", "tag_ids").
This should also fix #396
> [tagSceneswithPerfTags] add check before processing scene

- plugins/tagScenesWithPerfTags/tagScenesWithPerfTags.py
- plugins/tagScenesWithPerfTags/tagScenesWithPerfTags.yml
Adding an option that excludes a scene from the sceneUpdate and sceneCreate Hooks if the scene has a specific tag.
> [tagScenesWithPerfTags] add option to exclude a scene from the hook by tag

- plugins/TPDBMarkers/tpdbMarkers.py
When the `'movies'` key doesn't exist in the `scene` dictionary, a KeyError is thrown.
https://github.com/stashapp/CommunityScripts/blob/3dc70057e9b5a023842ed36ca5e8dcba25e0db33/plugins/TPDBMarkers/tpdbMarkers.py#L41
Instead, we can use the `get()` method, which will return `None` (or other default value) if the key does not exist, instead of raising a KeyError.
`len(scene["movies"])  >>  len(scene.get("movies", []))`
----
Resolves #440. Resolves #455.
> Uses dict.get() to avoid KeyError in TPDBMarkers plugin

- plugins/themeSwitch/themeSwitchMain.js
Fixes #390
Sometimes the css isn't loaded correctly cause `window.Location.origin` should be lowercase
> [themeSwitch] css loading fails with error

- plugins/setPerformersFromTags/README.md
- plugins/setPerformersFromTags/setPerformersFromTags.js
- plugins/setPerformersFromTags/setPerformersFromTags.yml
This PR adds the **"Set Performers From Tags"** plugin, which automatically assigns performers to scenes and images based on their tags.  
- Iterates through all scenes and images.  
- Matches performer names and aliases against scene/image tags.  
- Updates scenes and images with matched performers if necessary.  
This plugin is useful for users who have **tagged their media files with performer names** but haven't manually assigned performers. It helps **organize large libraries efficiently**, ensuring that performers are properly linked without manual input.
> Add plugin "Set Performers From Tags"

- plugins/pathParser/pathParser.js
Tried to configure the plugin and went down a debugging rabbit hole. These are the two bugs I've found so far. The tag creation and test tasks now work. Haven't got as far as testing the actual hook/run task functions yet.
I expect there are more dragons lurking in this code...
> Fix basic `pathParser` plugin functionality

- plugins/DateParser/date_parser.py
- plugins/DateParser/date_parser.yml
- Break out the date parsing to a separate function.
- Expand gallery search to more than single file zip galleries.
- Also scan the gallery's folder path if available.
The final valid parsed date of the files, then the gallery folder will be taken as the gallery's date. This will preserve the previous behavior of single file zip galleries, as there will be only one path to ever consider.
> Parse All Galleries for date

- plugins/TPDBMarkers/tpdbMarkers.py
This PR updates the TPDB Markers plugin to use the newer `find_groups()` method instead of the deprecated `find_movies()` method. This change resolves the deprecation warning while maintaining the same functionality.
`Warning 
[Plugin / The Porn DB Markers] find_movies() is depracated use find_gruops()`
- Replaced `stash.find_movies()` with `stash.find_groups()` in the `processMovie()` function
- Updated both instances where the method was used:
1. When checking for existing movies by URL
2. When searching for movies by title
The functionality remains the same, but now uses the recommended API method. The plugin will continue to:
- Process TPDB markers
- Create and associate movies with scenes
- Handle all existing features without the deprecation warning
Fixes deprecation warning.
> # Update TPDB Markers Plugin to Use find_groups()

- plugins/hotCards/hotCards.js
- plugins/hotCards/hotCards.yml
this adds two new style presets (silver and bronze) based on the style of the 'gold' preset. 
for example: r_5/4/3/2_gold/silver/bronze/none____///,50
i thought i would be useful for some as it was for me. 
now you can easily have a gold-silver-bronze rating for your hotCards.
> [hotCards] added silver and bronze default card style

- themes/Theme-Minimal/README.md
- themes/Theme-Minimal/Theme-Minimal.yml
- themes/Theme-Minimal/_theme.css
- themes/Theme-Minimal/inputs.css
- themes/Theme-Minimal/player.css
- themes/Theme-Minimal/popover.css
- themes/Theme-Minimal/scenes.css
- themes/Theme-Minimal/settings.css
- themes/Theme-Minimal/shared.css
- themes/Theme-Minimal/studio-performer-tagger.css
- themes/Theme-Minimal/studio.css
- Increase contrast for settings toggles
- Fix popover arrow theming
- Theme performer scraper
- Theme player vtt preview and markers
> [theme] minimal v0.2.4

- themes/Theme-Minimal/README.md
- themes/Theme-Minimal/Theme-Minimal.yml
- themes/Theme-Minimal/scenes.css
> [theme] minimal v0.2.6

- themes/Theme-Minimal/README.md
- themes/Theme-Minimal/Theme-Minimal.yml
- themes/Theme-Minimal/scenes.css
- Theme studio rating for real.
- Remove card hover.
> [theme] minimal v0.2.7

- plugins/externalLinksEnhanced/externalLinksEnhanced.js
- plugins/externalLinksEnhanced/externalLinksEnhanced.yml
Fixed bug where navigating to performer via Appears With would persist old links from the previous performer. This update removes stale links.
> External Links Enhanced: Bug fix for stale links

- plugins/stashNotifications/README.md
- plugins/stashNotifications/stashNotifications.css
- plugins/stashNotifications/stashNotifications.js
- plugins/stashNotifications/stashNotifications.yml
This plugin adds a notification button on the nav bar whenever you have out of date plugins and scrapers. You can then quickly update those plugins/scrapers on the fly.
When everything is up-to-date, the button is hidden.
> Added Stash Notifications

- plugins/timestampTrade/timestampTrade.py
- plugins/timestampTrade/timestampTrade.yml
This is a copy of #533 since it was closed without merge.
It wraps the connections to prevent connection when DB is in use.
- closes #310 
- closes #463
- closes #491
> [fix] [Timestamp Trade] Use context manager with connection to cleanup and reduce db locking

- plugins/tagScenesWithPerfTags/tagScenesWithPerfTags.py
- plugins/tagScenesWithPerfTags/tagScenesWithPerfTags.yml
This checks for `inputFields` on `hookContext`. This prevents an error that happened when scanning scenes for the first time.
> [tagScenesWithPerfTags] Add check if key exists

- plugins/bulkImageScrape/BulkImageScrape.yml
- plugins/bulkImageScrape/bulkImageScrape.py
- plugins/bulkImageScrape/requirements.txt
This plugin allows to apply a given image scraper (like SHALookup from FansDB) to images in bulk until stash supports something like this natively as it does for scenes.
For now it requires the most recent version of stashapi to be installed via the git repo directly (see requirements.txt) until the next stashapp-tools release.
> add bulkImageScraper Plugin

- plugins/miscTags/miscTags.py
- plugins/miscTags/miscTags.yml
Was never taging based on VRCompanionTags as the setting name is case sensitive.
> [plugins/miscTags] VRCompanionTags Not running

- plugins/bulkImageScrape/BulkImageScrape.yml
- plugins/bulkImageScrape/bulkImageScrape.py
The bulkImageScrape plugin used to request data of all images in the library in one big query at the beginning, which got really problematic on a very large library (like 250K images), leading to stash to first consume all the memory it can get and then die.
The new behavior uses page queries and a generator to process images in batches of 100.
I also added a plugin setting to skip a set number of entries, this was useful for runs that die midway through (for example due to scraper issues, etc).
I have no idea about the version number, so I just bumped it to a .1
> bulkImageScrape plugin now uses generator and paging to iterate images

- plugins/TPDBMarkers/tpdbMarkers.py
- plugins/timestampTrade/timestampTrade.py
Use `urls` instead of `url` so both plugins don't throw/exit when the create_movie to create_group shim in recent stashapi version is used.
> [timestampTrade] [tpdbMarkers] replace "url" with "urls"

- plugins/StashRandomButton/README.md
- plugins/StashRandomButton/random_button.js
- plugins/StashRandomButton/random_button.yml
This PR refactors and extends the Random Button plugin to support random navigation for all major entities in StashApp (scenes, images, performers, studios, groups, tags, galleries), both globally and internally. 
- Adds random selection for all entities and internal entity navigation (e.g. random scene in a studio, random image in a gallery).
- Updates README and manifest to reflect the new features.
Tested on v0.27.2+. Please let me know if any changes are required!
> [StashRandomButton] Add support for scenes, images, performers, studios, tags, groups and galleries

- plugins/StashRandomButton/README.md
- plugins/StashRandomButton/random_button.js
- plugins/StashRandomButton/random_button.yml
This PR improves the behavior and usability of the Random button across Stash pages, making navigation more intuitive and predictable.
- The Random button appears in the navigation bar on all main entity pages (scenes, images, performers, studios, groups, tags, galleries) and their internal pages (e.g. performer’s scenes, studio’s scenes, gallery’s images, etc).
- **Scenes:**  
- On the main scenes page, it picks a random scene from all scenes.
- On a performer/studio/tag/group *scenes* page, it picks a random scene from within that entity.
- On an individual scene’s detail page, clicking Random always picks a random scene from **all scenes** (regardless of how you arrived at that scene).
- **Images and Galleries:**  
- On the main galleries page, it picks a random gallery.
- On a …
> [StashRandomButton] Consistent Randomization on All Pages

- plugins/imageGalleryNavigation/README.md
- plugins/imageGalleryNavigation/imageGalleryNavigation.css
- plugins/imageGalleryNavigation/imageGalleryNavigation.js
- plugins/imageGalleryNavigation/imageGalleryNavigation.yml
This plugin adds features for navigating between images within a Gallery from the Image details page. This is intended to make it easier to edit metadata on each Image in a Gallery one at a time without constantly having to go back and forth between the Gallery and Image page.
This plugin currently adds two things to the Image details page:
- A line above the tabs in the left panel that indicates the current page and total number of pages in the current Gallery. The current image number can be changed to jump to a specific image within the Gallery.
- Buttons along the left/right side of the main Image display panel that allow moving to the previous/next image in the Gallery.
In the case of Images that are in multiple Galleries, the Gallery being navigated is set by accessing an Images …
> [imageGalleryNavigation] Initial commit.

- plugins/tagCopyPaste/README.md
- plugins/tagCopyPaste/tagCopyPaste.css
- plugins/tagCopyPaste/tagCopyPaste.js
- plugins/tagCopyPaste/tagCopyPaste.yml
This plugin adds Copy and Paste buttons next to the Tags input field that allows for easier bulk adding and copying of tags, with the goal of making it easy to copy Tags between objects, bulk load manually created tag lists, or load tag lists copied from AI tagger output.
The Copy button will create a comma delimited list of all currently entered tags and put this on your clipboard.
The Paste button will check your current clipboard for a comma delimited string and add these as Tags, optionally creating any missing tags. Pasted tags will be checked against both primary Tag names and all aliases, comparisons are not case sensitive and allow "_" to be interpreted as a space.
**Note**: This plugin will prompt you to grant access to the clipboard. This must be granted in order for this plugin …
> [tagCopyPaste] Initial Commit.

- plugins/tagCopyPaste/README.md
- plugins/tagCopyPaste/tagCopyPaste.js
- plugins/tagCopyPaste/tagCopyPaste.yml
A few small updates to tagCopyPaste.
- Adds newline as a valid delimiter for tag lists.
- Trim all input strings initially so trimming those values later is not necessary.
- Update README.
> [tagCopyPaste] Add newline as list delimiter. Trim all input. Update README.

- plugins/PlexSync/PlexSync.py
- plugins/PlexSync/PlexSync.yml
- plugins/PlexSync/README.md
- plugins/PlexSync/TODO.md
- plugins/PlexSync/requirements.txt
This is a plugin that is used in conjunction with https://github.com/Darklyter/StashPlexAgent.bundle -- despite this "constraint", it seems relevant to have it here.
The main purpose is that the Stash plugin refreshes metadata on Plex, when the relevant scene is updated in Stashapp. It also optionally cleans titles, and adds tags to scenes based on what stashbox it was sourced from.
Thanks!
> Add PlexSync plugin

- plugins/videoChapterMarkers/videoChapterMarkers.py
- plugins/videoChapterMarkers/videoChapterMarkers.yml
from what i can see, on stash 0.28.1 (latest stable release at time of writing) `Scene.Update.Post` gets called with only `args.hookContext` in json input. `args.mode` is only present for the `processAll` action when manually triggered in tasks section, and it is set like `args.mode == "processAll"`. the branch checking for `args.hookContext` was never reached as `args.mode` does not exist in these instances.
> [Video Chapter Markers] Fix on update trigger

- plugins/audio-transcodes/audio-transcodes.py
- plugins/audio-transcodes/audio-transcodes.yml
fixes audio transcodes with files that have spaces in them, forming a command using `%` (or any other string manipulation) is very dangerous at worst and wrong at best, this job should be handled by an appropriate library for running commands which can separate command arguments appropriately, aka subprocess.
also changes the ffmpeg command for audio transcodes to log fatal errors, otherwise the whole transcode log would show up as errors in stash even when it succeeded. also removes unnecessary logging of the whole stash configuration dict which can be several pages worth of scrolling while looking at logs.
> [audio-transcodes] Fix paths with spaces and ffmpeg stderr flood

- plugins/image_date_from_metadata/image_date_from_metadata.py
- plugins/image_date_from_metadata/image_date_from_metadata.yml
A plugin that retrieve "original taken date" from images (and gif/mp4 clips) metadata at creation time.
Also you can trigger it on all image without a gallery with a task
> Image date metadata finder plugin

- plugins/DateParser/date_parser.py
- plugins/DateParser/date_parser.yml
Added PythonDepManager to avoid people not installing dep
> Added PythonDepManager to avoid people not installing dep

- plugins/nfoSceneParser/config.py
- plugins/nfoSceneParser/nfoParser.py
- plugins/nfoSceneParser/nfoSceneParser.yml
- plugins/nfoSceneParser/stashInterface.py
Added possibility for nfoSceneParser plugin to configure:
- custom name of the nfo file
- name of the user rating field
- user rating multiplier
- source for tags
Additionally added:
- missing studio information on scene update
- "folder" as possible name for scene image
> [nfoSceneParser] new config options

- plugins/LocalVisage/LocalVisage.yml
- plugins/LocalVisage/frontend.js
- plugins/LocalVisage/readme.md
- plugins/LocalVisage/requirements.txt
The required stashuilibrary has changed name, version and repo. I updated it in consequence. I also had to change the requirement file for the venv due to some report of version conflicts
> [LocalVisage] Fixed major issue

- plugins/performerStashboxUrlToID/performerStashboxUrlToID.py
- plugins/performerStashboxUrlToID/performerStashboxUrlToID.yml
Adding a plugin to turn performer urls to a stash id.
This plugin works with a on performer update hook. If there is a url for stashdb, pmvstash, fansdb, javstash on that performer add that as a stashbox id for that performer.
Useful for when you tag a performer on one stashbox have it automatically add the other stashids for other stash boxes. eg: if you update the perfomer Angela White on stashdb this contains the url https://pmvstash.org/performers/43f5b81e-8424-4b6b-b8b8-d551a35dbb6a The plugin will then add the pmvstash  stashid: 43f5b81e-8424-4b6b-b8b8-d551a35dbb6a automatically if it isn't already there.
> Adding a plugin to turn performer urls to a stash id.

- plugins/performerStashboxUrlToID/performerStashboxUrlToID.py
- plugins/performerStashboxUrlToID/performerStashboxUrlToID.yml
This adds the TPDB domain to the list of valid stash boxes that can be detected by the "PerformerStashboxUrlToID" plugin. Because TPDB has multiple possible perfromer links, we need to add a check specific for links with the `/performers/` prefix that Stash-Box expects. This also adds a UUID check to make sure the Stash-Box ID is in the correct format, since TPDB is also a bit more relaxed about that.
> [PerformerStashboxUrlToID] Support TPDB performer URLs

- plugins/TPDBMarkers/tpdbMarkers.py
- plugins/timestampTrade/timestampTrade.py
This is a fix for  GraphQL validation in this two plugins. The other differences in the code is just formating /linting.
> Fix GraphQL Validation is Failing for timestampTrade and TPBMarkers

- plugins/defaultDataForPath/defaultDataForPath.js
See https://github.com/stashapp/CommunityScripts/issues/609 for full context.
Basically `path` field doesn't exist on `Gallery` and `findGallery` takes ` ID!` not `ID`.
the `path` value from `Folder` is _probably_ the best substitute, as it'll return something sane regardless if the gallery is a folder, zip, or comic-book-archive
> Fix issue #609

- plugins/DupFileManager/README.md
- plugins/FileMonitor/README.md
- plugins/RenameFile/README.md
- plugins/RenameFile/renamefile.js
- plugins/RenameFile/renamefile.py
- plugins/RenameFile/renamefile.yml
- plugins/RenameFile/renamefile_settings.py
- plugins/RenameFile/version_history/README.md
- Added setting max_performers to renamefile_settings.py, which allows limitting the quantity of performers added to file name. ### 0.5.9
- Added rename associated file feature. When video file is renamed, associated files will get renamed.
- Associated files are determind by file extensions listed in variable **associated_files_to_rename** which is in **renamefile_settings.py** file.
- Option **rename_associated_files_enable** can be used to disable this feature.  It's turned on by default. ### 1.0.0
- Fixed Dry-Run bug, which changed the file name in the database when Dry-Run was enabled.
> RenameFile Plugin - Changes for version 1.0.0 first full release version
