stashapp/CommunityScripts

PLUGINS-LIST.md
hook_plugins/renamerOnUpdate/README.md
hook_plugins/renamerOnUpdate/log.py
hook_plugins/renamerOnUpdate/renamerOnUpdate.py
hook_plugins/renamerOnUpdate/renamerOnUpdate.yml

Everytime you update a scene, it will check if new information are added/removed then change the filename if needed.
Work for Windows10 at least 😅 
Exemple (Template used: `$date $title`)
- Scan
- Found Stash_test.mp4
- Edit Scene, add the date **2021-06-19**
- Save
- The file become 2021-06-19 Stash_test.mp4
- Edit Scene, change title to **Stash_plugins**
- Save
- The file become 2021-06-19 Stash_plugins.mp4

[Hook Plugins] Scene.Update - Renamer

---

scripts/Sqlite_Renamer/README.md
scripts/Sqlite_Renamer/Stash_Sqlite_Renamer.py

Using same term as the Hook plugins and fixed things.

[Script] Rework Renamer

---

plugins/renamerOnUpdate/README.md
plugins/renamerOnUpdate/renamerOnUpdate.py

If you want to use parent studio in your filename.
Exemple:
`RealityKings 2016-12-29 Eva Lovia - Her Fantasy Ball.mp4`

[Renamer Hook] Adding Parent Studio as field

---

PLUGINS-LIST.md
plugins/GHScraper_Checker/GHScraper_Checker.py
plugins/GHScraper_Checker/GHScraper_Checker.yml
plugins/GHScraper_Checker/log.py

I am pretty sure that this plugins could work with a stash version < v0.8.
Require **Request** module 
- Status Check
Show in log if you miss a scraper file, or a new update of this scraper exist.
- Getting new files
Only get file that don't exist in your scraper folder.
- Overwrite everything
Commented in .yml because i don't want to miss-click on this button.
It will overwrite all your scrapers files, will remove personal things like API Key.

[Plugin] Github scraper checker

---

3rd party/StashPlexAgent.bundle/Contents/Code/__init__.py
3rd party/StashPlexAgent.bundle/Contents/DefaultPrefs.json
3rd party/StashPlexAgent.bundle/Contents/Info.plist
3rd party/StashPlexAgent.bundle/README.md

Full bundle is included, put into "3rd party' directory to segment from Stash based scripts

Initial commit of Plex metadata agent to pull Stash data

---

plugins/tagGraph/log.py
plugins/tagGraph/requirements.txt
plugins/tagGraph/stash_interface.py
plugins/tagGraph/tag_graph.py
plugins/tagGraph/tag_graph.yml

generates a visualization of the current tag hierarchy as a graph

tagGraph Plugin

---

plugins/setSceneCoverFromFile/log.py
plugins/setSceneCoverFromFile/set_cover.py
plugins/setSceneCoverFromFile/set_scene_cover.yml
plugins/setSceneCoverFromFile/stash_interface.py

plugin to set scene covers from unique images found in the same folder as the scene file

Set cover from file

---

PLUGINS-LIST.md
plugins/renamer/README.md
plugins/renamer/config.py
plugins/renamer/log.py
plugins/renamer/renamerTask.py
plugins/renamer/renamerTask.yml

Same thing as renamerOnUpdate but is trigger by a Task.
Should solve #12 
Draft: need more test

Create renamer as Task Plugin

---

scripts/Sqlite_Renamer/Stash_Sqlite_Renamer.py

[Script] Update Stash_Sqlite_Renamer.py

---

plugins/renamer/renamerTask.py
plugins/renamer/renamerTask.yml

Fixes issue #37 for the Renamer Task plugin

[Plugin/renamer] Fix issue #37

---

plugins/renamerOnUpdate/config.py
plugins/renamerOnUpdate/renamerOnUpdate.py
plugins/renamerOnUpdate/renamerOnUpdate.yml

- Adding Plugin Task to disable/enable the hook
- Rename file associated to the video file (Subtitle, funscript) #46
- ⚠️ Changed `performer_ignore_male` to `performer_ignoreGender` so you can choose other gender as well.
- Add option to put your filename in lowercase
- Add option to replace space from Stash field (title, performer, studio, ...)
- Add option to remove specific character from filename, By default `,#` ,these character was before in the regex to remove illegal character in windows. User didn't know why these character wasn't on the filename so it should be more clear now.
- Add option to remove prepositions from the beginning of titles.
- ❗ ⚠️ ❗ Changed the regex to create the filename, it should be better but report if it's not correct. #28 
- ⚠️ Audio & Video codec always …

[renamerOnUpdate] Associate file, On/Off Hook, more option

---

README.md
plugins/defaultDataForPath/README.md
plugins/defaultDataForPath/defaultDataForPath.js
plugins/defaultDataForPath/defaultDataForPath.yml

I've written a plugin to specify default data to add on scene/image/gallery creation for certain filepaths

Add defaultDataForPath plugin

---

README.md
themes/plex/README.md
themes/plex/plex.css

Will be moving themes here starting with the Plex one, as per https://github.com/stashapp/stash/issues/2741#issuecomment-1183786833
I've applied the updates that came up in that issue to the theme as well.
Went with the approach of each theme having its own folder so that a `README` file can be present and automatically visible when in the folder for the theme.

add and update plex theme

---

plugins/defaultDataForPath/defaultDataForPath.js
plugins/defaultDataForPath/defaultDataForPath.yml

There were two null checks missing from the code which has the potential to cause errors depending on configuration. Null checks have been added and the fix has been verified

[plugins][defaultDataForPath] Fix small bug causing null assertions

---

README.md
userscripts/StashDB_Submission_Helper/README.md
userscripts/StashDB_Submission_Helper/stashdb_submission_helper.user.js

This PR adds a folder for userscripts as well as ports over one of my userscripts to this repo

[userscripts][stashdb submission helper] Add userscripts section and stashdb submission helper userscript

---

plugins/renamerOnUpdate/renamerOnUpdate.py
plugins/renamerOnUpdate/renamerOnUpdate.yml
plugins/renamerOnUpdate/renamerOnUpdate_config.py

fix #73 
People on discord said it work for them so I guess i can public this branch, but like always use it at your **own risk** since it edit directly your database ⚠️ 
- Support file-refactor update (Stash v17.0)
- Add `$date_format` field. You can change the format of the date.
- Add `$duration` field.
- Add `duplicate_suffix` in order to support multiple file for one scene.
- Changed filename of config and other to have "renamerOnUpdate" inside.
Draft until FileRefactor is pushed and more testing.
Issue reported:
> template group don't work
> prevent_consecutive = True but still end up with consecutive folders

[renamerOnUpdate] File refactor update

---

README.md
plugins/titleFromFilename/README.md
plugins/titleFromFilename/config.py
plugins/titleFromFilename/graphql.py
plugins/titleFromFilename/log.py
plugins/titleFromFilename/requirements.txt
plugins/titleFromFilename/titleFromFilename.py
plugins/titleFromFilename/titleFromFilename.yml

titleFromFilename sets the title of a scene after it is created to its filename.
It is only needed for the builds after the files refactor as the functionality was removed with that PR

[plugin] Add titleFromFilename plugin

---

plugins/renamerOnUpdate/renamerOnUpdate.py
plugins/renamerOnUpdate/renamerOnUpdate.yml
plugins/renamerOnUpdate/renamerOnUpdate_config.py

I was sure it was already a option...

[renamerOnUpdate] Option to append dry-run log

---

plugins/titleFromFilename/titleFromFilename.py
plugins/titleFromFilename/titleFromFilename.yml

Retry scene update requests as they seem to fail often

[titleFromFilename] Retry update requests

---

plugins/renamerOnUpdate/renamerOnUpdate.py
plugins/renamerOnUpdate/renamerOnUpdate.yml

Fixes #93 
Looks like this was originally some copypasta from Line 400. 
Right now I've bumped it to the same version as I have in #92. Didn't want to make any assumptions/requirements that one is merged before the other.

[renamerOnUpdate] Fix typo in studio handling in get_template_filename

---

plugins/renamerOnUpdate/renamerOnUpdate.py
plugins/renamerOnUpdate/renamerOnUpdate.yml
plugins/renamerOnUpdate/renamerOnUpdate_config.py

Option to ignore performer without gender defined.
#95

[renamerOnUpdate] option to ignore undefined gender

---

plugins/renamerOnUpdate/renamerOnUpdate.py
plugins/renamerOnUpdate/renamerOnUpdate.yml
plugins/renamerOnUpdate/renamerOnUpdate_config.py

[renamerOnUpdate] more field

---

plugins/renamerOnUpdate/renamerOnUpdate.py
plugins/renamerOnUpdate/renamerOnUpdate.yml

[renamerOnUpdate] fix performer rating

---

plugins/renamerOnUpdate/renamerOnUpdate.py
plugins/renamerOnUpdate/renamerOnUpdate.yml

- Fix studio_code order.
- Fix if the user don't have the `code` migration #111

[renamerOnUpdate] fix bug

---

plugins/renamerOnUpdate/renamerOnUpdate.py
plugins/renamerOnUpdate/renamerOnUpdate.yml

option `field_whitespaceSeperator` removed character from path and other thing that shouldn't be change.

[renamerOnUpdate] fix field_whitespaceSeperator

---

plugins/renamerOnUpdate/renamerOnUpdate.py
plugins/renamerOnUpdate/renamerOnUpdate.yml

Changed how the field was detected/changed in the template. It should solve issue #96 #79 
Need more testing, if people can test and report if this change too many thing in your template. Use Dryrun

[renamerOnUpdate] changed the rename method

---

plugins/renamerOnUpdate/renamerOnUpdate.py
plugins/renamerOnUpdate/renamerOnUpdate.yml

[renamerOnUpdate] fix replace_words

---

plugins/renamerOnUpdate/README.md
plugins/renamerOnUpdate/renamerOnUpdate.py
plugins/renamerOnUpdate/renamerOnUpdate.yml

The option to remove some field to reduce the path length was removed in FileRefactor update.
This PR add this back.
#119

[renamerOnUpdate] adding back reduce path option

---

plugins/timestampTrade/timestampTrade.py

- fixes #170 with JSON error handling
- display debug message if no markers for scene
- added explicit exit if no scenes to process

[timestamptrade] error handling, logging

---

plugins/timestampTrade/timestampTrade.py

Discussed with Tweeticoats, builds on top of https://github.com/stashapp/CommunityScripts/pull/172

[timestamptrade] add Skip Sync and Skip Submit meta-tags

---

plugins/dupeMarker/README.md
plugins/dupeMarker/dupeMarker.py
plugins/dupeMarker/dupeMarker.yml
plugins/dupeMarker/requirements.txt

This plugin marks exact duplicate markers for manual removal by the user

Add dupeMarker

---

README.md

first attempt at prepping for v24 changes - just updating the readme.

updating readme to add the start of v24 upgrade tracking

---

plugins/4. CropperJS/CropperJS.yml
plugins/4. CropperJS/cropper.css
plugins/4. CropperJS/cropper.js
plugins/sceneCoverCropper/sceneCoverCropper.js
plugins/sceneCoverCropper/sceneCoverCropper.yml

original userscript code by @scruffynerf

Add CropperJS and Scene Cropper as JS plugins

---

plugins/filenameParser/filenameParser.js

This is useful for the galleries that are compacted in a zip file

[filenameParser] Add zip format to blocklist

---

README.md

just cleaning up my 'main' so I can have a clean fork...

Prep for v24 changes to repo organization of new plugins and fixes of older ones

---

themes/Theme-PornHub/Theme-PornHub.css
themes/Theme-PornHub/Theme-PornHub.yml

add PH theme

---

plugins/stats/stats.js

the query changed, and the code hadn't....

fixes query that aged badly

---

themes/Theme-RoundedYellow/README.md
themes/Theme-RoundedYellow/Theme-RoundedYellow.css
themes/Theme-RoundedYellow/Theme-RoundedYellow.yml

I want to share my Stash Theme featuring rounded corners and a yellow accent color.

[Theme] - Adding RoundedYellow Theme

---

plugins/filenameParser/filenameParser.js

Small modifications just to get it working, probably can be improved by a lot

Update filenameParser.js to work with v0.24.3

---

plugins/renamerOnUpdate/renamerOnUpdate.py

Converts a filename to title case. Capitalizes all words except for certain conjunctions, prepositions, and articles, unless they are the first or last word of a segment of the filename. Recognizes standard apostrophes, right single quotation marks (U+2019), and left single quotation marks (U+2018) within words.
Ignores all caps words and abbreviations, e.g., MILF, BBW, VR, PAWGs. Ignores words with mixed case, e.g., LaSirena69, VRCosplayX, xHamster. Ignores resolutions, e.g., 1080p, 4k.

[renamerOnUpdate] Updates capitalizeWords to better handle edge cases

---

.github/workflows/on_pr_check_code_format.yml
.github/workflows/on_push_check_code_format.yml
.gitignore
.prettierrc.json
plugins/CropperJS/cropper.js
plugins/StashBatchResultToggle/stashBatchResultToggle.js
plugins/defaultDataForPath/defaultDataForPath.js
plugins/filenameParser/filenameParser.js
plugins/pathParser/pathParser.js
plugins/sceneCoverCropper/sceneCoverCropper.js
plugins/stashAI/stashai.js
plugins/stashRealbooru/stash-realbooru.js
plugins/stashUserscriptLibrary/stashUserscriptLibrary.js
plugins/stats/stats.js
plugins/visage/visage.js
userscripts/StashDB_Submission_Helper/stashdb_submission_helper.user.js

Thanks to [Hijack Hornet](https://discord.com/channels/559159668438728723/559159910550732809/1206020199359320184) for pointing out this issue on discord.

Fix trailing comma

---

userscripts/StashDB_Submission_Helper/stashdb_submission_helper.user.js

I've updated my username, so updating the references here.

update halorrr username

---

plugins/themeSwitch/themeSwitchMain.js

So sorry again, just saw the example. And was flustered so didn't think. Sorry about the extended Github Actions on this

[plugin - themeSwitch] rm export default

---

plugins/TPBDMarkers/TPDBMarkers.yml
plugins/TPBDMarkers/tpdbMarkers.py

Changed to new domain for TPDB.
FYI, @Tweeticoats

TPDB domain change

---

plugins/stashUserscriptLibrary/stashUserscriptLibrary.js

This removes all the userscript_functions plugin related code.
Removed Methods:
- getConfigValueTask
- updateConfigValueTask
- createSystemSettingTextbox
- createSystemSettingCheckbox
- addSystemSetting
- createSettings
- getPluginVersion
- processApiKey
- hidePluginTasks
- comparePluginVersion
Removed Events:
- stash:pluginVersion
- stash:plugin:task
Removed Properties:
- visiblePluginTasks
- settingsCallbacks
- pluginVersion
It's all custom settings functionality that's been made obsolete by Stash's built-in support for plugin settings and I don't believe any plugins other than my own ever made use of them. None of the existing scripts and plugins referenced any of these methods, events, and properties so it should be ok to remove although I haven't tested the plugins in this repo yet.

Remove userscript functions plugin and obsolete settings related functions

---

plugins/timestampTrade/timestampTrade.py
plugins/timestampTrade/timestampTrade.yml

This should hopefully fix movie processing by removing the old code that didn't always work.

Bugfixes, mainly to remove old code that didn't quite work and use the version that did

---

plugins/comicInfoExtractor/comicInfoExtractor.yml

remove absolute path to python

---

plugins/miscTags/miscTags.py
plugins/miscTags/miscTags.yml
plugins/stashdb-performer-gallery/stashdb-performer-gallery.py

If there is the "solo" tag and 1 performer it will add the "Solo Female", "Solo Male", "Solo Trans" tags.
If there is a "Threesome" tag add the group makeup ie "Threesome (BBG)" based on the gender of the performers.

Updating misc-Tags to add group support.

---

.vscode/extensions.json
.vscode/settings.json
schema/plugin.schema.json

Added schema for YAML plugin config files.
Added VSCode configuration file to automatically check and provide completion for YAML files in plugins and themes folders.
Added recommended extension for VSCode to make all of the above work.

Add plugins JSON schema and VSCode configuration to use it

---

scripts/Sqlite_Renamer/README.md
scripts/Sqlite_Renamer/Stash_Sqlite_Renamer.py
scripts/Sqlite_Renamer/requirements.txt

Also added a requirements.txt file for progressbar2
The rename mechanic was not changed, only the database queries and some validations that were added

Update renamer for new db schema

---

plugins/VideoScrollWheel/VideoScrollWheel.js

fix inconsistent plugin name (#320)

---

plugins/stats/stats.js
plugins/stats/stats.yml

add new stats to ExtendedStats

---

plugins/CommunityScriptsUILibrary/README.md
plugins/CommunityScriptsUILibrary/cs-ui-lib.js

Add documentation, also expose `basePath`

add JSDoc and README for cs-ui-lib

---

plugins/markerTagToScene/markerTagToScene.js
plugins/markerTagToScene/markerTagToScene.yml

Add the ability to add all tags and not just the primary tag to the scene
Add config to control above behavior
Add a task to run over all markers in database

Add multiple tags and task to markerToSceneTag

---

plugins/defaultDataForPath/defaultDataForPath.js

Declare result as a variable prior to assignment.

Update defaultDataForPath.js: s/result =/var result =/g

---

plugins/defaultDataForPath/defaultDataForPath.js

path[s] result on findImage returns web paths, we need file path instead.

Update defaultDataForPath.js fix getImagePath query and update object

---

plugins/AITagger/ai_tagger.py
plugins/AITagger/ai_video_result.py
plugins/AITagger/tag_mappings.csv

Add support for all the different possible csv filenames before the json migration for storing raw ai results

[AI Tagger] Add better backwards compatibility with scenes tagged in the csv era

---

plugins/tagScenesWithPerfTags/requirements.txt
plugins/tagScenesWithPerfTags/tagScenesWithPerfTags.py
plugins/tagScenesWithPerfTags/tagScenesWithPerfTags.yml

This is my plugin for taking performer tags (race, breast size, tattoos etc. etc.) and applying them to scenes they appear in.

Tag scenes with performer tags plugin

---

themes/Theme-Pornhub inspired/pornhub-inspired.css
themes/Theme-Pornhub inspired/pornhub-inspired.yml

Source & credit https://github.com/stashapp/stash/discussions/3884

Add Pornhub inspired theme

---

plugins/hotCards/hotCards.yml

Missing CommunityScriptsUILibrary require in yml file.

Fix csLib is not defined

---

plugins/hotCards/hotCards.js
plugins/hotCards/hotCards.yml

- use ?. to not fail when loading from `{}`
- use Object.values instead of Object.entries
- clean up regex with repeating patterns
- use pathname to pre-strip parameters
- move css to bottom, to ensure depencies load first

[hotcards] add ?. fallbacks and clean regex, fix dependency chain

---

plugins/AdulttimeInteractiveDL/AdulttimeInteractiveDL.py

- proper debugging for exception catching
- exit instead of return in main
- unindent funscript download and conversion from cache file
no longer exists immediately and also works when not running from cache alone

misc fixes for adulttimeinteractive

---

plugins/hotCards/README.md
plugins/hotCards/hotCards.css
plugins/hotCards/hotCards.js
plugins/hotCards/hotCards.yml

Key features added:
- Customizable Hot Cards.
- Flexibility to choose tag-based or rating-based for each card type with different values if desired.
- Two more style presets in addition to the default.
- Support for 0-5 explicit Rating Threshold alongside 6-100 range for tenths.

[Hot Cards] Customizable Hot Cards

---

plugins/discordPresence/README.md
plugins/discordPresence/discordPresence.js
plugins/discordPresence/discordPresence.yml

Rewrote the server component as my own app, because the original was unreliable and crashed/froze on minor errors. Refactored this plugin to use a new server app and added continuous retries if the websocket connection between stash and the server app is lost, as well as overall refactoring.

discordPresence refactor with new server app

---

plugins/RenameFile/README.md
plugins/RenameFile/renamefile.py
plugins/RenameFile/renamefile.yml
plugins/RenameFile/renamefile_settings.py
plugins/RenameFile/requirements.txt

Add plugin from https://github.com/David-Maisonave/Axter-Stash/tree/main/plugins/RenameFile
Author: @David-Maisonave

Add RenameFile plugin

---

plugins/hotCards/hotCards.js
plugins/hotCards/hotCards.yml
plugins/hotCards/utils/fetchInterceptor.js
plugins/hotCards/utils/helpers.js
plugins/hotCards/utils/registerPathChangeListener.js
plugins/hotCards/utils/stashHandler.js

I think utility files should be in this repository instead of being referenced to a personal repository. Also, in case any changes are made to them (mostly unlikely), it can be tracked.

[Hot Cards] Add utility files and update CDNs

---

plugins/hotCards/hotCards.yml

I had a brainfart when added the utility files.

[Hot Cards] Replace CDNs with local files

---

plugins/AdulttimeInteractiveDL/AdulttimeInteractiveDL.py
plugins/AdulttimeInteractiveDL/AdulttimeInteractiveDL.yml
plugins/PythonToolsInstaller/PythonToolsInstaller.py
plugins/PythonToolsInstaller/PythonToolsInstaller.yml

- remove unused imports
- remove unreachable code

remove indirect pythontoolsintealler from adulttimeinteractive

---

userscripts/FansDB_Submission_Helper/fansdb_submission_helper.user.js

Refactor URL logic based on #444
Add check to skip unmatched URLs

Update FansDB Submisison Helper

---

plugins/CommunityScriptsUILibrary/README.md
plugins/CommunityScriptsUILibrary/cs-ui-lib.js

Adds a new feature to csLib.
You can now *write* the plugin configuration!

[csLib] Now capable of writing the plugin config !

---

README.md
archive/README.md

Continuing discussion from [discord](https://discord.com/channels/559159668438728723/1310051794604265553) and [new platform]
- simplified language
- reduced timeline from 30d -> 14d
- broader scope for deprecation (no version requirement)
- move to "archive" folder instead of deleting

formalized tl;dr of deprecation policy

---

plugins/timestampTrade/requirements.txt
plugins/timestampTrade/timestampTrade.py

Revert https://github.com/stashapp/CommunityScripts/commit/4c9aaa5e1cce61699c7fa4f3e4c19e7415fdf183 which breaks compatibility 
Add specific stashapp-tools version to requirmentents.txt instead

[timestampTrade] Revert breaking change

---

plugins/markerTagToScene/markerTagToScene.js

This plugins logs lot of JSON and other info. I disable JSON log and convert other one from Info to Debug.

[markerTagToScene] reduce logging

---

plugins/ExtraPerformerInfo/extraPerformerInfo.py
plugins/ExtraPerformerInfo/extraPerformerInfo.yml

This is mainly for performer awards but can also add some extra urls and other information as well.

Adding a plugin to add extra performer information from wikidata.

---

plugins/themeSwitch/themeSwitch.yml
plugins/themeSwitch/themeSwitchMain.js

Fix #437 (Theme Switcher Plugin)

---

themes/Theme-Minimal/README.md
themes/Theme-Minimal/Theme-Minimal.yml
themes/Theme-Minimal/index.css
themes/Theme-Minimal/nav-bar.css
themes/Theme-Minimal/scenes.css
themes/Theme-Minimal/studio.css

It's now recommended to disable studio images in card view.
- Themed the tagger view for a more cohesive look.
- Restyled and refactored the navbar for improved usability and aesthetics.
- Restyled all the scene card information overlays to enhance clarity and visual appeal.
- Fixed the scene card selector to ensure proper functionality.
- Fixed scene auto play.

[theme] Minimal 0.2 Release

---

themes/Theme-Minimal/README.md
themes/Theme-Minimal/Theme-Minimal.yml
themes/Theme-Minimal/nav-bar.css

- Fix content offset from nav-bar.

[theme] minimal 0.2.1 

---

themes/Theme-Minimal/README.md
themes/Theme-Minimal/Theme-Minimal.yml
themes/Theme-Minimal/_theme.css
themes/Theme-Minimal/inputs.css
themes/Theme-Minimal/nav-bar.css
themes/Theme-Minimal/player.css
themes/Theme-Minimal/popover.css
themes/Theme-Minimal/scene-tagger.css
themes/Theme-Minimal/scenes.css
themes/Theme-Minimal/skeleton.css
themes/Theme-Minimal/stats.css
themes/Theme-Minimal/studio-tagger.css

- Theme popover arrow.
- Theme card size slider.
- Theme studio tagger.
- Theme scene tagger search result.
- Theme skeleton.
- Center stats.

[theme] Minimal v0.2.2

---

plugins/videoChapterMarkers/README.md
plugins/videoChapterMarkers/requirements.txt
plugins/videoChapterMarkers/videoChapterMarkers.py
plugins/videoChapterMarkers/videoChapterMarkers.yml

The `Video Chapter Markers` plugin extracts and creates scene markers from video chapters.

Add plugin "Video Chapter Markers" 

---

themes/Theme-Minimal/README.md
themes/Theme-Minimal/Theme-Minimal.yml
themes/Theme-Minimal/scenes.css

- Theme tag card view.
- Rework studio/tag card backgrounds.

[theme] minimal v0.2.5

---

plugins/miscTags/miscTags.py

Scene VR releases tagged with vr180 in filename was not getting any tags.

Add vr180 to VRCTags

---

plugins/e621_tagger/e621_tagger.py
plugins/e621_tagger/e621_tagger.yml

- added `e621_tag_failed` - this tag appeares of its failed to tag the image (exception or e621 api error)
- marking images as categorized when tagged
- added pagination to prevent OOM Killing

e621_tagger new features

---

plugins/imageGalleryNavigation/README.md

Just a simple README update so that it reflects the other recent merge.

[imageGalleryNavigation] Update README.
